# Generated by Django 4.0.4 on 2022-10-26 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Curriculum'), ('CE', 'Curriculum + Entrevista'), ('S', 'Sorteio'), ('OI', 'Ordem de inscrição')], default='C', max_length=2, verbose_name='tipo de avaliação')),
                ('publico_alvo', models.CharField(choices=[('A', 'Alunos'), ('C', 'Colaboradores'), ('I', 'Internos')], default='A', max_length=1, verbose_name='público alvo')),
                ('numero', models.CharField(max_length=255, unique=True, verbose_name='número do edital')),
                ('ano', models.CharField(max_length=255, verbose_name='ano do edital')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('campi', models.ManyToManyField(to='processoseletivo.campus')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'edital',
                'verbose_name_plural': 'editais',
                'ordering': ['-ano', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeOrganizadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_completa', models.CharField(help_text='Ex.: DG/ZL/RE/IFRN, PROEN/IFRN', max_length=255, verbose_name='tipo de avaliação')),
            ],
            options={
                'verbose_name': 'unidade organizadora',
                'verbose_name_plural': 'unidades organizadoras',
                'ordering': ['sigla_completa'],
            },
        ),
        migrations.CreateModel(
            name='TipoArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processoseletivo.edital')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documentos',
                'ordering': ['edital', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='edital',
            name='unidade_organizadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processoseletivo.unidadeorganizadora'),
        ),
    ]
